extend:
  jaxon-joint-simulator-arm_layout.yaml

main:
  rarm q:
    legends:
      - { key: st_q, id: [17],label: st_collar-y }
      - { key: st_q, id: [18],label: st_shoulder-p }
      - { key: st_q, id: [19],label: st_shoulder-r }
      - { key: st_q, id: [20],label: st_shoulder-y }
      - { key: st_q, id: [21],label: st_elbow-p }
      - { key: st_q, id: [22],label: st_wrist-y }
      - { key: st_q, id: [23],label: st_wrist-r }
      - { key: st_q, id: [24],label: st_wrist-p }
      # - { key: abc_q, id: [17],label: abc_collar-y }
      # - { key: abc_q, id: [18],label: abc_shoulder-p }
      # - { key: abc_q, id: [19],label: abc_shoulder-r }
      # - { key: abc_q, id: [20],label: abc_shoulder-y }
      # - { key: abc_q, id: [21],label: abc_elbow-p }
      # - { key: abc_q, id: [22],label: abc_wrist-y }
      # - { key: abc_q, id: [23],label: abc_wrist-r }
      # - { key: abc_q, id: [24],label: abc_wrist-p }
      - { key: abst_q, id: [17],label: abst_collar-y }
      - { key: abst_q, id: [18],label: abst_shoulder-p }
      - { key: abst_q, id: [19],label: abst_shoulder-r }
      - { key: abst_q, id: [20],label: abst_shoulder-y }
      - { key: abst_q, id: [21],label: abst_elbow-p }
      - { key: abst_q, id: [22],label: abst_wrist-y }
      - { key: abst_q, id: [23],label: abst_wrist-r }
      - { key: abst_q, id: [24],label: abst_wrist-p }
      # - { key: el_q, id: [17],label: el_collar-y }
      # - { key: el_q, id: [18],label: el_shoulder-p }
      # - { key: el_q, id: [19],label: el_shoulder-r }
      # - { key: el_q, id: [20],label: el_shoulder-y }
      # - { key: el_q, id: [21],label: el_elbow-p }
      # - { key: el_q, id: [22],label: el_wrist-y }
      # - { key: el_q, id: [23],label: el_wrist-r }
      # - { key: el_q, id: [24],label: el_wrist-p }
      - { key: RobotHardware0_q, id: [17],label: rh_collar-y }
      - { key: RobotHardware0_q, id: [18],label: rh_shoulder-p }
      - { key: RobotHardware0_q, id: [19],label: rh_shoulder-r }
      - { key: RobotHardware0_q, id: [20],label: rh_shoulder-y }
      - { key: RobotHardware0_q, id: [21],label: rh_elbow-p }
      - { key: RobotHardware0_q, id: [22],label: rh_wrist-y }
      - { key: RobotHardware0_q, id: [23],label: rh_wrist-r }
      - { key: RobotHardware0_q, id: [24],label: rh_wrist-p }
      - { key: enc_q, id: [17], label: enc_collar-y }
      - { key: enc_q, id: [18], label: enc_shoulder-p }
      - { key: enc_q, id: [19], label: enc_shoulder-r }
      - { key: enc_q, id: [20], label: enc_shoulder-y }
      - { key: enc_q, id: [21], label: enc_elbow-p }
      - { key: enc_q, id: [22], label: enc_wrist-y }
      - { key: enc_q, id: [23], label: enc_wrist-r }
      - { key: enc_q, id: [24], label: enc_wrist-p }
    bottom_label:
    newline: false

  larm q:
    legends:
      - { key: st_q, id: [25],  label: st_collar-y }
      - { key: st_q, id: [26],  label: st_shoulder-p }
      - { key: st_q, id: [27],  label: st_shoulder-r }
      - { key: st_q, id: [28],  label: st_shoulder-y }
      - { key: st_q, id: [29], label: st_elbow-p }
      - { key: st_q, id: [30], label: st_wrist-y }
      - { key: st_q, id: [31], label: st_wrist-r }
      - { key: st_q, id: [32], label: st_wrist-p }
      # - { key: abc_q, id: [25],  label: abc_collar-y }
      # - { key: abc_q, id: [26],  label: abc_shoulder-p }
      # - { key: abc_q, id: [27],  label: abc_shoulder-r }
      # - { key: abc_q, id: [28],  label: abc_shoulder-y }
      # - { key: abc_q, id: [29], label: abc_elbow-p }
      # - { key: abc_q, id: [30], label: abc_wrist-y }
      # - { key: abc_q, id: [31], label: abc_wrist-r }
      # - { key: abc_q, id: [32], label: abc_wrist-p }
      - { key: abst_q, id: [25],  label: abst_collar-y }
      - { key: abst_q, id: [26],  label: abst_shoulder-p }
      - { key: abst_q, id: [27],  label: abst_shoulder-r }
      - { key: abst_q, id: [28],  label: abst_shoulder-y }
      - { key: abst_q, id: [29], label: abst_elbow-p }
      - { key: abst_q, id: [30], label: abst_wrist-y }
      - { key: abst_q, id: [31], label: abst_wrist-r }
      - { key: abst_q, id: [32], label: abst_wrist-p }
      # - { key: el_q, id: [25],  label: el_collar-y }
      # - { key: el_q, id: [26],  label: el_shoulder-p }
      # - { key: el_q, id: [27],  label: el_shoulder-r }
      # - { key: el_q, id: [28],  label: el_shoulder-y }
      # - { key: el_q, id: [29], label: el_elbow-p }
      # - { key: el_q, id: [30], label: el_wrist-y }
      # - { key: el_q, id: [31], label: el_wrist-r }
      # - { key: el_q, id: [32], label: el_wrist-p }
      - { key: RobotHardware0_q, id: [25],label: rh_collar-y }
      - { key: RobotHardware0_q, id: [26],label: rh_shoulder-p }
      - { key: RobotHardware0_q, id: [27],label: rh_shoulder-r }
      - { key: RobotHardware0_q, id: [28],label: rh_shoulder-y }
      - { key: RobotHardware0_q, id: [29],label: rh_elbow-p }
      - { key: RobotHardware0_q, id: [30],label: rh_wrist-y }
      - { key: RobotHardware0_q, id: [31],label: rh_wrist-r }
      - { key: RobotHardware0_q, id: [32],label: rh_wrist-p }
      - { key: enc_q, id: [25], label: enc_collar-y }
      - { key: enc_q, id: [26], label: enc_shoulder-p }
      - { key: enc_q, id: [27], label: enc_shoulder-r }
      - { key: enc_q, id: [28], label: enc_shoulder-y }
      - { key: enc_q, id: [29], label: enc_elbow-p }
      - { key: enc_q, id: [30], label: enc_wrist-y }
      - { key: enc_q, id: [31], label: enc_wrist-r }
      - { key: enc_q, id: [32], label: enc_wrist-p }
    bottom_label:

  arm ServoState:
    legends:
      - { key: ServoState, id: [17], label: r-collar-y }
      - { key: ServoState, id: [18], label: r-shoulder-p }
      - { key: ServoState, id: [19], label: r-shoulder-r }
      - { key: ServoState, id: [20], label: r-shoulder-y }
      - { key: ServoState, id: [21], label: r-elbow-p }
      - { key: ServoState, id: [22], label: r-wrist-y }
      - { key: ServoState, id: [23], label: r-wrist-r }
      - { key: ServoState, id: [24], label: r-wrist-p }
      - { key: ServoState, id: [25], label: l-collar-y }
      - { key: ServoState, id: [26], label: l-shoulder-p }
      - { key: ServoState, id: [27], label: l-shoulder-r }
      - { key: ServoState, id: [28], label: l-shoulder-y }
      - { key: ServoState, id: [29], label: l-elbow-p }
      - { key: ServoState, id: [30], label: l-wrist-y }
      - { key: ServoState, id: [31], label: l-wrist-r }
      - { key: ServoState, id: [32], label: l-wrist-p }
    bottom_label:
    newline: false

  arm 12V:
    legends:
      - { key: 12V, id: [17], label: r-collar-y }
      - { key: 12V, id: [18], label: r-shoulder-p }
      - { key: 12V, id: [19], label: r-shoulder-r }
      - { key: 12V, id: [20], label: r-shoulder-y }
      - { key: 12V, id: [21], label: r-elbow-p }
      - { key: 12V, id: [22], label: r-wrist-y }
      - { key: 12V, id: [23], label: r-wrist-r }
      - { key: 12V, id: [24], label: r-wrist-p }
      - { key: 12V, id: [25], label: l-collar-y }
      - { key: 12V, id: [26], label: l-shoulder-p }
      - { key: 12V, id: [27], label: l-shoulder-r }
      - { key: 12V, id: [28], label: l-shoulder-y }
      - { key: 12V, id: [29], label: l-elbow-p }
      - { key: 12V, id: [30], label: l-wrist-y }
      - { key: 12V, id: [31], label: l-wrist-r }
      - { key: 12V, id: [32], label: l-wrist-p }
    newline: false

  arm 80V:
    legends:
      - { key: 80V, id: [17], label: r-collar-y }
      - { key: 80V, id: [18], label: r-shoulder-p }
      - { key: 80V, id: [19], label: r-shoulder-r }
      - { key: 80V, id: [20], label: r-shoulder-y }
      - { key: 80V, id: [21], label: r-elbow-p }
      - { key: 80V, id: [22], label: r-wrist-y }
      - { key: 80V, id: [23], label: r-wrist-r }
      - { key: 80V, id: [24], label: r-wrist-p }
      - { key: 80V, id: [25], label: l-collar-y }
      - { key: 80V, id: [26], label: l-shoulder-p }
      - { key: 80V, id: [27], label: l-shoulder-r }
      - { key: 80V, id: [28], label: l-shoulder-y }
      - { key: 80V, id: [29], label: l-elbow-p }
      - { key: 80V, id: [30], label: l-wrist-y }
      - { key: 80V, id: [31], label: l-wrist-r }
      - { key: 80V, id: [32], label: l-wrist-p }

  # rarm abs/enc diff:
  #   legends:
  #     - { key: abs_enc_diff, id: [17], label: collar-y }
  #     - { key: abs_enc_diff, id: [18], label: shoulder-p }
  #     - { key: abs_enc_diff, id: [19], label: shoulder-r }
  #     - { key: abs_enc_diff, id: [20], label: shoulder-y }
  #     - { key: abs_enc_diff, id: [21], label: elbow-p }
  #     - { key: abs_enc_diff, id: [22], label: wrist-y }
  #     - { key: abs_enc_diff, id: [23], label: wrist-r }
  #     - { key: abs_enc_diff, id: [24], label: wrist-p }
  #   newline: false

  # larm abs/enc diff:
  #   legends:
  #     - { key: abs_enc_diff, id: [25], label: collar-y }
  #     - { key: abs_enc_diff, id: [26], label: shoulder-p }
  #     - { key: abs_enc_diff, id: [27], label: shoulder-r }
  #     - { key: abs_enc_diff, id: [28], label: shoulder-y }
  #     - { key: abs_enc_diff, id: [29], label: elbow-p }
  #     - { key: abs_enc_diff, id: [30], label: wrist-y }
  #     - { key: abs_enc_diff, id: [31], label: wrist-r }
  #     - { key: abs_enc_diff, id: [32], label: wrist-p }
