extend:
  st_layout.yaml

main:
  rleg_torque:
    legends:
      # - { key: torque, id: [0], label: r-hip-y }
      # - { key: torque, id: [1], label: r-hip-r }
      - { key: torque, id: [2], label: r-hip-p }
      - { key: torque, id: [3], label: r-knee-p }
      - { key: torque, id: [4], label: r-ankle-p }
      - { key: torque, id: [5], label: r-ankle-r }
    newline: false

  lleg_torque:
    legends:
      # - { key: torque, id: [6], label: l-hip-y }
      # - { key: torque, id: [7], label: l-hip-r }
      - { key: torque, id: [8], label: l-hip-p }
      - { key: torque, id: [9], label: l-knee-p }
      - { key: torque, id: [10], label: l-ankle-p }
      - { key: torque, id: [11], label: l-ankle-r }

  rleg_q:
    legends:
      # - { key: st_q, id: [0], label: r-hip-y }
      # - { key: st_q, id: [1], label: r-hip-r }
      - { key: st_q, id: [2], label: r-hip-p }
      - { key: st_q, id: [3], label: r-knee-p }
      - { key: st_q, id: [4], label: r-ankle-p }
      - { key: st_q, id: [5], label: r-ankle-r }
      # - { key: RobotHardware0_q, id: [0], label: r-hip-y }
      # - { key: RobotHardware0_q, id: [1], label: r-hip-r }
      - { key: RobotHardware0_q, id: [2], label: r-hip-p }
      - { key: RobotHardware0_q, id: [3], label: r-knee-p }
      - { key: RobotHardware0_q, id: [4], label: r-ankle-p }
      - { key: RobotHardware0_q, id: [5], label: r-ankle-r }
    newline: false

  lleg_q:
    legends:
      # - { key: st_q, id: [6], label: l-hip-y }
      # - { key: st_q, id: [7], label: l-hip-r }
      - { key: st_q, id: [8], label: l-hip-p }
      - { key: st_q, id: [9], label: l-knee-p }
      - { key: st_q, id: [10], label: l-ankle-p }
      - { key: st_q, id: [11], label: l-ankle-r }

  rleg_dq:
    legends:
      # - { key: RobotHardware0_dq, id: [0], label: r-hip-y }
      # - { key: RobotHardware0_dq, id: [1], label: r-hip-r }
      - { key: RobotHardware0_dq, id: [2], label: r-hip-p }
      - { key: RobotHardware0_dq, id: [3], label: r-knee-p }
      - { key: RobotHardware0_dq, id: [4], label: r-ankle-p }
      - { key: RobotHardware0_dq, id: [5], label: r-ankle-r }
    newline: false

  lleg_dq:
    legends:
      # - { key: RobotHardware0_dq, id: [6], label: l-hip-y }
      # - { key: RobotHardware0_dq, id: [7], label: l-hip-r }
      - { key: RobotHardware0_dq, id: [8], label: l-hip-p }
      - { key: RobotHardware0_dq, id: [9], label: l-knee-p }
      - { key: RobotHardware0_dq, id: [10], label: l-ankle-p }
      - { key: RobotHardware0_dq, id: [11], label: l-ankle-r }
