main:
  act/ref cog zmp:
    legends:
      - { key: st_originActCog, id: [0-2]}
      - { key: st_originRefCog, id: [0-2]}
      - { key: st_originActZmp, id: [0-2]}
      - { key: st_originRefZmp, id: [0-2]}
      - { key: st_originNewZmp, id: [0-2]}

  act/ref cog velocity:
    legends:
      - { key: st_originActCogVel, id: [0-2]}
      - { key: st_originRefCogVel, id: [0-2]}

  act/ref root-link relative zmp:
    legends:
      - { key: st_zmp, id: [0-1] }
      - { key: abc_zmpOut, id: [0-1] }
    newline: false

  optional_data:
    legends:
      - { key: abc_contactStates, id: [0], label: rleg }
      - { key: abc_contactStates, id: [1], label: lleg }

  act/ref force:
    legends:
      - { key: rmfo_off_rfsensor, id: [0-2] }
      - { key: rmfo_off_lfsensor, id: [0-2] }
      - { key: st_ref_rfsensor, id: [0-2] }
      - { key: st_ref_lfsensor, id: [0-2] }

  act/ref moment:
    legends:
      - { key: rmfo_off_rfsensor, id: [3-5] }
      - { key: rmfo_off_lfsensor, id: [3-5] }
      - { key: st_ref_rfsensor, id: [3-5] }
      - { key: st_ref_lfsensor, id: [3-5] }

  moment comp:
    legends:
      - { key: st_rfcomp, id: [3-4] }
      - { key: st_lfcomp, id: [3-4] }
    newline: false

  force comp:
    legends:
      - { key: st_rfcomp, id: [2] }
      - { key: st_lfcomp, id: [2] }

  act/ref base rpy:
    legends:
      - { key: sh_baseRpyOut, id: [0-2] }
      - { key: st_currentBaseRpy, id: [0-2] }
      - { key: st_actBaseRpy, id: [0-2] }

  act/ref base rpy vel:
    legends:
      - { key: sh_baseRpyVel, id: [0-2] }
      - { key: st_currentBaseRpyVel, id: [0-2] }
      - { key: st_actBaseRpyVel, id: [0-2] }

  # optional_data:
  #   legends:
  #     - { key: abc_contactStates, id: [0-3] }
  #     - { key: abc_controlSwingSupportTime, id: [0-3] }
